- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: grafana-config
    namespace: monitoring
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: freenas-nfs-csi
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: grafana-storage
    namespace: monitoring
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: freenas-nfs-csi
